<?php
require Mage::getBaseDir('lib') . '/kint/Kint.class.php';

class BlueAcorn_GreenspecDiscounts_Helper_Data extends Mage_Core_Helper_Abstract
{
    public function write_variable($variable, $fileName)
    {
        ob_start();
        d($variable);
        $result = ob_get_flush();
        $fp = fopen(Mage::getBaseDir('log') . DIRECTORY_SEPARATOR . $fileName, 'w');
        fwrite($fp, $result);
        fclose($fp);
    }

    public function generateCouponCodes(array $parameters = array('format' => 'alphanumeric'))
    {
        $rule = Mage::getModel('salesrule/rule')->load(5); // 5 is 5% off referral coupon ID

        // Define a coupon code generator
        // Look at Mage_SalesRule_Model_Coupon_Massgenerator for options
        $generator = Mage::getModel('salesrule/coupon_massgenerator');

        if (!empty($parameters['format'])) {
            switch (strtolower($parameters['format'])) {
                case 'alphanumeric':
                case 'alphanum':
                    $generator->setFormat(Mage_SalesRule_Helper_Coupon::COUPON_FORMAT_ALPHANUMERIC);
                    break;
                case 'alphabetical':
                case 'alpha':
                    $generator->setFormat(Mage_SalesRule_Helper_Coupon::COUPON_FORMAT_ALPHABETICAL);
                    break;
                case 'numeric':
                case 'num':
                    $generator->setFormat(Mage_SalesRule_Helper_Coupon::COUPON_FORMAT_NUMERIC);
                    break;
            }
        }

        $generator->setDash(!empty($parameters['dash_every_x_characters']) ? (int)$parameters['dash_every_x_characters'] : 0);
        $generator->setLength(!empty($parameters['length']) ? (int)$parameters['length'] : 8);
        $generator->setPrefix(!empty($parameters['prefix']) ? $parameters['prefix'] : '');
        $generator->setSuffix(!empty($parameters['suffix']) ? $parameters['suffix'] : '');

        // Set the generator, and coupon type so it's able to generate
        $rule->setCouponCodeGenerator($generator);
        $rule->setCouponType(Mage_SalesRule_Model_Rule::COUPON_TYPE_AUTO);

        // Get as many coupons as you required
        $count = !empty($parameters['count']) ? (int)$parameters['count'] : 1;
        $codes = array();
        for ($i = 0; $i < $count; $i++) {
            $coupon = $rule->acquireCoupon();
            $coupon
                ->setType(Mage_SalesRule_Helper_Coupon::COUPON_TYPE_SPECIFIC_AUTOGENERATED)
                ->save();

            $code = $coupon->getCode();

            if ($count == 1) {
                return $code;
            } else {
                $codes[] = $code;
            }
        }
        return $codes;
    }
}